### ISSUE TITLE
openapi doesn't work with sphinx 1.6.1

### ISSUE THREAD

**Issue by kazuki** [ikalnytskyi/sphinxcontrib-openapi#12]
```
$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.6.1
making output directory...
loading translations [ja]... 
/usr/local/lib/python3.6/site-packages/sphinxcontrib/openapi.py:23: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 1.7, please use the standard library version instead.
  from sphinx.util.compat import Directive

Exception occurred:
  File "/usr/local/lib/python3.6/site-packages/sphinxcontrib/openapi.py", line 195, in setup
    if 'http' not in app.domains:
AttributeError: 'Sphinx' object has no attribute 'domains'
The full traceback has been saved in /tmp/sphinx-err-f5_cfbju.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:55: recipe for target 'html' failed
make: *** [html] Error 1
```

I think https://github.com/sphinx-doc/sphinx/issues/3760 is same issue.

**Comment by ikalnytskyi** [comment]
Thanks for the report! I'll take a look what I can do. :)

**Comment by ikalnytskyi** [comment]
@kazuki FYI: the new version has been released and is available on PyPI (https://pypi.python.org/pypi/sphinxcontrib-openapi).

**Comment by kazuki** [comment]
Thank!
